name: Sync Branches

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Auto-sync all branches to main
        run: |
          # Get all remote branches except main
          BRANCHES=$(git branch -r | grep -v 'origin/main' | grep -v 'origin/HEAD' | sed 's/origin\///' | tr -d ' ')
          
          echo "Found branches to sync: $BRANCHES"
          
          for branch in $BRANCHES; do
            echo "Syncing branch: $branch"
            
            # Checkout or create the branch
            git checkout "$branch" 2>/dev/null || git checkout -b "$branch" "origin/$branch"
            
            # Reset to main and push
            git reset --hard origin/main
            git push origin "$branch" --force-with-lease
            
            echo "✅ Synced $branch with main"
          done